### ISSUE TITLE
Atmos breach problem still happening

### ISSUE THREAD

**Issue by Bawhoppen** [tgstation/tgstation#18123]
same problem as before, the PR to fix it didn't actually help at all

**Comment by xxalpha** [comment]
But who the fuck knows what was the "problem as before".

**Comment by MrStonedOne** [comment]
ya, what "breach problem".

**Comment by ike709** [comment]
Add "Issue with no description" tag

**Comment by Bawhoppen** [comment]
you guys must never play if you don't know what this is

https://github.com/tgstation/tgstation/issues/17814

**Comment by MrStonedOne** [comment]
I knew about that issue, but i didn't know you were referring to that issue.

You can not assume people will make the same connections in their mind that you do.

If you had said space or cold i would have figured it out, but you said breach and i assumed it was relating to canatmospass and a bug that was fixed around windows some times not blocking atmos.

**Comment by Bawhoppen** [comment]
ok well you know now what I meant

**Comment by Bawhoppen** [comment]
The actual air part of this has been fixed however spacewind sucks everything from basically the opposite side of the damn map out breaches still

**Comment by Bawhoppen** [comment]
this is still happening its so annoying, remove that damn needs reproducing tag it happens whether you try to make it or not

**Comment by PKPenguin321** [comment]
how to reproduce:
1. get an RPD
2. go to escape
3. spray pipes on every tile in escape
4. open one of the sets of two airlocks to space at escape
5. observe the vast amount of pipes removed from the station before the airlocks close themselves again
6. observe how the air is still mostly livable, but wind has practically emptied it

**Comment by MrStonedOne** [comment]
This is all intended, space wind removes air, other tiles with more air equalize out, it's just how our atmos system works.

**Comment by Bawhoppen** [comment]
it didn't used to be like this where literally the entire hallway drained of items into one spot

**Comment by MrStonedOne** [comment]
That's because atmos was running too slow from lavaland

**Comment by Bawhoppen** [comment]
long before lavaland it was like that though

**Comment by Cyberboss** [comment]
@lzimann Closable
