### ISSUE TITLE
Null crates have nothing in them

### ISSUE THREAD

**Issue by evsey9** [tgstation/tgstation#20335]
There is nothing in null crates

**Comment by TheRealGLH** [comment]
Looks like they're truly 'null' crates :^)

**Comment by evsey9** [comment]
It's not fun wasting 140K on empty crates.
Also that joke have been made already, its unoriginal.

**Comment by optimumtact** [comment]
Sounds like a feature to me

**Comment by evsey9** [comment]
#20266 didn't fix this

**Comment by Jalleo** [comment]
@iamgoofball.

**Comment by xxalpha** [comment]
Looks like someone fixed the null crate.

**Comment by evsey9** [comment]
Haha how original.

**Comment by optimumtact** [comment]
This is fixed AFAIK.

**Comment by evsey9** [comment]
I am going to record me ordering null crates on a private server and send the footage server

**Comment by evsey9** [comment]
Its still not fixed

**Comment by evsey9** [comment]
https://www.youtube.com/watch?v=wa3vUfqLsJo&feature=youtu.be The video is sdhit but you get the point ITS NOT FIXED!!!!

**Comment by evsey9** [comment]
REEEEEEEEEEEEEEEEEEEEE

**Comment by Shadowlight213** [comment]
Caused by an edge case.
If you order a null crate before anyone opens an uplink, the list the crate tries to pick from isn't initialized.

**Comment by evsey9** [comment]
Wait. 
How could you even get an emagged cargo console before anyone opens an uplink?
Or, does the link get un-initialized when an uplink is closed?
I am not good at byond coding.
I am too lazy to learn BYOND.

**Comment by optimumtact** [comment]
The bug is striking you because you're admin spawning the emag and the crates I assume?

**Comment by Shadowlight213** [comment]
@optimumtact yup. That's why it was occurring for me.
I was admin spawning the emag and using it to order crates.

**Comment by evsey9** [comment]
But there were nothing in the null crate even when i was a traitor on TG and ordered an emag and then emagged the console and ordered null crates.

**Comment by nullbear** [comment]
I've seen people order null crates and receive loot.
