### ISSUE TITLE
Half of the game screen are just black tiles

### ISSUE THREAD

**Issue by Web-Mang** [tgstation/tgstation#21066]
Problem Description: Half of my game screen is black

What did you expect to happen: The tiles shouldn't be pitch black
What happened instead: The tiles are pitch black
Why is this bad/What are the consequences: Makes playing the game almost impossible

Steps to reproduce the problem: Joined the game, signed up as a cook, half of arrivals and everything else was just black

Server: Basil and Sybil

Revision: Server revision compiled on: 2016-10-19
Test merge active of PR #20869 
Based off master commit c735825107da9c76196669f68004341cc092c976 
Current Infomational Settings:
Protect Authority Roles From Traitor: 1
Protect Assistant Role From Traitor: 0
Enforce Human Authority: 1
Allow Latejoin Antagonists: 1
Enforce Continuous Rounds: 10 of 20 roundtypes
Allow Midround Antagonists: 7 of 20 roundtypes
Game Mode Odds:
blob 4.8%
traitorchan 21.7%
double_agents 12%
traitor 15.7%
clockwork_cult 6%
cult 4.8%
extended 1.2%
nuclear 16.9%
revolution 8.4%

Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?): I launched the game in the middle of the round and when I joined it was just black. It's only an issue on tg severs. I took a screenshot of what it looks like if it helps: http://imgur.com/a/1odHS

**Comment by LanCartwright** [comment]
Is your client updated?

**Comment by optimumtact** [comment]
Update to the latest 511 client

**Comment by optimumtact** [comment]
This one
http://www.byond.com/download/build/511/511.1360_byond.exe

**Comment by Web-Mang** [comment]
Updating doesn't seem to fix the problem unfortunately

**Comment by optimumtact** [comment]
@MrPerson @AnturK @MrStonedOne

**Comment by Durkel** [comment]
Did you try clearing your cache?

**Comment by AnturK** [comment]
Interesting.

What OS ? Hardware/software mode ?

**Comment by MrPerson** [comment]
Also GPU would be useful.

Only other suggestion is to make sure your GPU's drivers are up to date.

**Comment by YakumoChen** [comment]
is your Internet Explorer up to date

**Comment by Web-Mang** [comment]
I've cleared my cache, I have a Windows 10 and a GTX 960M. I had been playing an hour before and it was working fine, just kind of odd

**Comment by Web-Mang** [comment]
Whenever I go into ghost mode the game looks fine, but when I'm actually alive it's all messed up. Don't know if this helps I just wanna play some good old tg

**Comment by MrStonedOne** [comment]
Right click on the start menu button and choose device manager, expand display adapter, right click your gpu and select uninstall

Make sure delete driver software is unchecked, then click ok, you will be asked to restart, restart, log in, then restart once more. Should fix it.

**Comment by MrStonedOne** [comment]
Alternatively, admins can edit a client's control_freak to 0, then tell the client right click the ss13 icon, go to client -> preferences -> uncheck use graphics hardware for displaying maps then repeat the same steps to check it again.

**Comment by MrStonedOne** [comment]
For anybody affected: Open pager/hub (the main byond application where you log in) And click the white gear/cog icon in the top right and go to preferences (or press control+p). Go to games then make sure that "Use graphics hardware for displaying maps" is checked.

Reconnect to the game and that SHOULD fix it

**Comment by Web-Mang** [comment]
I tried doing the thing where you uninstall your gpu, but it still doesn't work, and everything seems to be the way it was before

**Comment by Web-Mang** [comment]
Could it be my Intel graphics driver?

**Comment by MrStonedOne** [comment]
>Open pager/hub (the main byond application where you log in) And click the white gear/cog icon in the top right and go to preferences (or press control+p). Go to games then make sure that "Use graphics hardware for displaying maps" is checked.

do these steps and tell me if they work.

**Comment by Web-Mang** [comment]
The entire game screen is white when its turned on, looks like this: http://imgur.com/a/ZrWNc

**Comment by MrStonedOne** [comment]
Hmm, you said you have both intel and nvidia graphics cards? hmm I would try disabling the intel one in device manager.

**Comment by Web-Mang** [comment]
Oh thank god that fixed it, my screens at a weird resolution but who cares. Thanks broseph

**Comment by MrStonedOne** [comment]
that might mean your monitor is plugged to the wrong slot (ie, not plugged in to the GTX)

**Comment by Web-Mang** [comment]
I have a laptop so most likely not?

**Comment by Web-Mang** [comment]
Not sure what happened because I didn't change anything but now when I disable my Intel graphics card it still has the black tiles. I didn't change anything, I just got on Sybil and it was like that

**Comment by optimumtact** [comment]
see also #21264

**Comment by optimumtact** [comment]
#21264 has the best report so closing this in favour of that one
