### ISSUE TITLE
Gamemode code will assign people to candidates for antag when they do not need to be

### ISSUE THREAD

**Issue by Zelacks** [tgstation/tgstation#4443]
##### Revision that this bug was encountered on (REQUIRED!! Type 'show-server-revision' ingame to find out - note that 'current revision' isn't helpful!):

74c22755be237bf3252dcab72da6cf0100b3490d
##### Which server were you playing on? (REQUIRED!! e.g. TG-Sibyl1, TG-Sibyl2, Badgerstation, Facepunch, Pinkstation, /VG/... etc.)

/tg/station private server
##### Problem Description

Because of the reccomended_enemies variable, when a gamemode asks for candidates for the gamemode, it will receive a larger pool than it wants.

For example with the traitor gamemode. If you have 12 players (coeff of 6), the gamemode only wants 2 traitors. If of those 12 people, only 2-3 people have traitor preferences enabled (also not security), the gamemode interface will add all 12 players to the candidate pool

This is because of the recommended_enemies variable, which is set to 4. If there is less than the reccommended_enemies ready and selected for traitor, it adds non-antag flagged players to the pool.
###### What did you expect to happen?

From the example above. If 12 people are available, and the gamemode needs 2 antags, and 2-3 people are flagged to be an antag, then the gamemode will use them as the antags.
###### What happened instead?

The entire 12 players were selected as the pool for antags.
###### Why is this bad/What are the consequences?

The game unnecessarily adds people who do not want to play antag to the pool of  candidates.
##### Anything else?

I was working on a fix, but I hit a road block so currently I am not "claiming" this issue, but I have started it, finishing the fix maybe never. I have a lot of other work to do so I am likely not to finish making a fix

**Comment by Jalleo** [comment]
related to #3162

**Comment by MrStonedOne** [comment]
I think this was fixed. @Incoming5643 @RemieRichards

**Comment by Zelacks** [comment]
game mode code is poorly designed, the code for getting candidates seem to be both a mix of code written in the gamemode class as well as the lower level definitions. I really, really highly doubt that there is even antags before job selection, I am still looking at everything but oh god.

**Comment by Zelacks** [comment]
oh god why is this code copy pasted twice

**Comment by Zelacks** [comment]
no the issue is not solved, and requires basically redesigning roundstart code. The gamemode should determine how many bad guys it wants depending on the situation, and then gather candidates. Currently, it gathers as many people as it can, but if it does not meet the recommended_enemies, it will add more candidates than needed, even if the gamemode needs less than the recommended_enemies

**Comment by MrStonedOne** [comment]
@Incoming5643

**Comment by Incoming5643** [comment]
>no the issue is not solved, and requires basically redesigning roundstart code.

Boy are you in luck

**Comment by tedward1337** [comment]
Seems to be unfixable unless someone wants to rewrite roundstaat code

**Comment by Zelacks** [comment]
blockquote, div.yahoo_quoted { margin-left: 0 !important; border-left:1px #715FFA solid !important; padding-left:1ex !important; background-color:white !important; }  Correct, its the game mode base code that is flawed from the start, it's been awhile but basically the game mode controller arbitrarily only gives the game mode a certain pool to work with leading to obtuse and weird code to get what the mode needs. What should happen is the game mode (child) type should either have full access to all clients and decide what it wants to do, or atleast ask the game mode controller to supply it with x amount of antags, rather than the parent attempting to predict how many antags it needs
It's a big deal so this SHOULD NOT be tagged as can't fix/won't fix


Sent from Yahoo Mail for iPad


On Sunday, October 30, 2016, 6:21 am, tedward1337 <notifications@github.com> wrote:


Seems to be unfixable unless someone wants to rewrite roundstaat code

**Comment by MrStonedOne** [comment]
Please don't reply via email using yahoo, they add extra shit to the reply that doesn't need to exist and it fucks up in the github issue page.

In fact, you shouldn't be using yahoo at all, they suck.

**Comment by nicbn** [comment]
This still not solved?
