### ISSUE TITLE
Fakedeath forever

### ISSUE THREAD

**Issue by Krysonism** [tgstation/tgstation#49518]
## Testmerges:
#49233: 'Paintings icons and persistence.' by AnturK at commit 6042cba7c3
#49065: 'Disable library machine uis' by optimumtact at commit f261fc0b45
#49111: '[READY]Arconomy: Sales Taggers, split profits on barcoded, sold items!' by ArcaneMusic at commit 50d52bd564

## Reproduction: No idea

Like 15-20 people were permanently stuck in fake death.

 I am unsure if this was caused by regen coma or zombie powder caused this but i suspect regen coma since most patients had a beneficial virus.

**Comment by XDTM** [comment]
Regen coma and some source of constant damage (like flesh-eating) could achieve this, since regen coma only stops when healed enough. If nanites were involved it could potentially be a bug, although as far as i know that one should already have been fixed.

**Comment by ArcaneDefence** [comment]
Likely caused by microdoses of ingested zombie powder, which puts people into a permanent fake death, that is not fixed by actually dying and being revived. Purging them with water and potassium does not fix this either. The only fix I am aware of is to feed them like 2u of zombie powder.

Methods to recreate;
Feed <1u in a beaker
Damp rag with <1u to the mouth
Smokes dipped in a small quantity of zombie powder
Small quantities of zombie powder in a smoke grenade
Small quantities added to food via syringe

**Comment by XDTM** [comment]
#46931 broke it by making it bypass on_mob_metabolize

**Comment by Shadowflame909** [comment]
Wow.

Didn't expect this...Who uses 1 unit of ZP? Considering toxins drain out instantly if it's under 2u.

Eventually, Kars stopped thinking.
