### ISSUE TITLE
Cyber-Arms and Arcade Games

### ISSUE THREAD

**Issue by TrueWOPR** [tgstation/tgstation#49777]
Issue reported from  Round ID: 131669 (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

Reporting client version: 513.1507

Simply put, augmented arms (affixed through amputation or augmentation) function as if amputated - your character will only look and sigh.

As for the "nanotrasen pocket arcade" available on the PCs and Tablets on the station, while the first monster will load, none of the buttons function - can't attack, defend, or magic.

Thought I should make both of these known - the former is far more important than the latter.

**Comment by Timberpoes** [comment]
> 
> 
> Issue reported from Round ID: 131669 (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])
> 
> Reporting client version: 513.1507
> 
> Simply put, augmented arms (affixed through amputation or augmentation) function as if amputated - your character will only look and sigh.
> 
> As for the "nanotrasen pocket arcade" available on the PCs and Tablets on the station, while the first monster will load, none of the buttons function - can't attack, defend, or magic.
> 
> Thought I should make both of these known - the former is far more important than the latter.

#49792 should fix the prosthetics not working.

**Comment by TrueWOPR** [comment]
Thank you Timberpoes.  I wish I could help contribute more directly but I made the fatal mistake of learning ActionScript back in school because...  you know... I thought the ability to play games in browser with minimal download was the future.

Keeping open for now so the Arcade Machine bug is still noticed.

**Comment by Timberpoes** [comment]
> 
> 
> Thank you Timberpoes. I wish I could help contribute more directly but I made the fatal mistake of learning ActionScript back in school because... you know... I thought the ability to play games in browser with minimal download was the future.
> 
> Keeping open for now so the Arcade Machine bug is still noticed.

No worries. The arcade game on NTOS systems is now fixed separately in #49823 

Do these two fixes address all your problems? Even if they do, please keep this open. The issues should automatically be closed when the appropriate PRs are processed and if there's anything else that pops up people can add to it.

**Comment by TrueWOPR** [comment]
Oh, cool!  I'll close then, thank you!
