### ISSUE TITLE
Megafauna abilities are broken

### ISSUE THREAD

**Issue by Striders13** [tgstation/tgstation#63886]
## Round ID:
[176132](https://scrubby.melonmesa.com/round/176132), also tested locally

## Testmerges:
#63558: 'makes hud images only show to mobs on the same z level to save on maptick' by Kylerace at commit daa26c1ecd
#63750: 'lowers kilo's bombcap multiplier' by Fikou at commit 16e2d0383d
#63331: 'Revert "Require Node 16"' by MrStonedOne at commit 3bccf7f8c1

## Reproduction:
Normally megafauna mobs are supposed to be "stunned" when doing abilities, unable to walk or attack. 
But right now they try to walk away or hit you during their attacks (like bubblegum charge). Their melee apparently has no cooldown too.
Videos of older codebase from 21 oct 2021 and new one included

#63520 is probably the reason this happens

https://user-images.githubusercontent.com/53361823/148449057-dcbe6d6a-845d-4234-969c-9874c7da1664.mp4

https://user-images.githubusercontent.com/53361823/148449358-521f904d-f94c-4fe7-9612-61a78047b66a.mp4

**Comment by mixzombie** [comment]
I can confirm Ashdrakes are behaving the same way.

**Comment by AdipemDragon** [comment]
ah, so THAT's the difference, yeah no sorry couldn't get it in the moment when ya called us in to look at it

**Comment by dragomagol** [comment]
Can confirm, this button doesn't work on main servers.

**Comment by tralezab** [comment]
Reportedly fixed in #68382 but I'll leave this open to test it myself tomorrow. If everything looks fine I'll close it

**Comment by Sealed101** [comment]
did u test it arm

**Comment by Striders13** [comment]
s(he) be(lie)ve(d)

**Comment by Sealed101** [comment]
tested, attack speed and after-action shenanigans are still present
