### ISSUE TITLE
Light plane issues or something?

### ISSUE THREAD

**Issue by FlamingCheese** [tgstation/tgstation#69667]
## Round ID:
[189716](https://scrubby.melonmesa.com/round/189716) ,189709

## Testmerges:
#69632 #69634 #69181 

## Reproduction:
![image](https://user-images.githubusercontent.com/75639936/188167147-2ae7699e-b1b9-43d2-a36e-b05295baff56.png)
![image](https://user-images.githubusercontent.com/75639936/188168356-e20d7288-40cc-4afa-85b8-5f6b48444fd7.png)
![image](https://user-images.githubusercontent.com/75639936/188168001-3c7b4986-a3f3-473f-a858-080315fd046b.png)

Walk around the map and some items/creatures are absurdly bright

**Comment by timothymtorres** [comment]
Might be related to what is causing #69666

**Comment by LemonInTheDark** [comment]
This makes me think that they're being marked as emissive somehow. It doesn't replicate on my local tho?

**Comment by LemonInTheDark** [comment]
oh nope absolutely does replicate

**Comment by LemonInTheDark** [comment]
Resolved

**Comment by FlamingCheese** [comment]
![image](https://user-images.githubusercontent.com/75639936/188317828-3af44e87-c110-4b52-927c-1a88655d1266.png)
![image](https://user-images.githubusercontent.com/75639936/188317868-e7072fc2-041f-4f38-b149-17e42dd72069.png)
@LemonInTheDark issue still appears on 189839 and 189851

**Comment by LemonInTheDark** [comment]
yeah I haven't updated the pr yet, no worries
