### ISSUE TITLE
Photographs don't show janicart nor windows

### ISSUE THREAD

**Issue by AssassinT90** [tgstation/tgstation#7092]
Photographs do not show whole-tile windows.

They also do not capture the janicart.

They also do not get fire lights.

Nor Plasma.

Fix that shit.

**Comment by Chocobro** [comment]
photographs don't show a lot of things, i've been compiling an image for quite some time but no better time than this to post it.
http://i.imgur.com/jnLmrsX.png

**Comment by Jalleo** [comment]
Chocobro what is the reason for the photographs to not work so well?

**Comment by Miauw62** [comment]
photographs are weird magic, i don't know how they work exactly.

**Comment by RemieRichards** [comment]
it's a LOT of dark getFlatIcon() magic.

**Comment by Chocobro** [comment]
jalleo I don't know the slightest about dm code I cannot tell you how this bug is caused

**Comment by Jalleo** [comment]
thats fine RemieRichards explained it

**Comment by tedward1337** [comment]
Fixed by #8658

**Comment by phil235** [comment]
fulltile windows still do no appear.

**Comment by Cyberboss** [comment]
Janitorial cart definitely does not appear. I did a VV on a janitorial cart vs a grille (both are direct subtypes of obj/structure). They had virtually no differences. So I checked the icons the only difference I can tell is grilles have a green alpha background, while carts have a grey alpha background. Does that mean anything?

**Comment by octareenroon91** [comment]
This issue persists. It seems also that closets stop showing up after they've been moved.

**Comment by Alek2ander** [comment]
It seems that getFlatIcon just fails on windows. Possibly caused by #23922?
On the other hand getFlatIcon only fails on a few specific space turfs, like 147,76,1 on box, but photos fail to show any space turf, possibly caused by parallax.
