### ISSUE TITLE
Air injectors look like they're off.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#7166]
Could be similar to #4382, where it's just an icon thing, but I don't know if they don't actually work.

This happens on both the station and away missions. They're supposed to be green, not dark red.
http://i.imgur.com/ReleQ14.png
http://i.imgur.com/mNUrC0Z.png

@menshin
@Aranclanos

**Comment by Actionb** [comment]
I can confirm that at least the injector at the turbine is not working.

**Comment by Menshin** [comment]
Outlet injectors (a.k.a incinerators) are _off_ by default. If you want them to be _on_, use the /.../outlet_injector/on subtype.

This is more a mapping issue, since outlet injectors are controllable via the radio controller : either they start on or one should add a way to toggle them on the map.

**Comment by WJohn** [comment]
They used to start on, some recent change must have done something about that. I'll run through a bunch of maps and try to have them all turned on.

**Comment by WJohn** [comment]
This has been fixed, by the way.

**Comment by WJohn** [comment]
Looks like this never got fixed for away missions. They still look like they're off there, it works fine on the station though.

**Comment by Anonus** [comment]
Air injectors need to be in a powered area, or they won't stay on.

**Comment by phil235** [comment]
Still a problem.
In Metastation virology: there's an injector that is off. And there's even a second injector two tile above it, on the same tile as another pipe, clearly a map error on Metastation.

There's also an off injector on box Virology. Always because the injector is in the space area so not powered.

**Comment by WJohn** [comment]
This is due to lacking areas. Will get to.
