### ISSUE TITLE
Chemical Press UI is broken

### ISSUE THREAD

**Issue by Lutowski** [tgstation/tgstation#80576]
## Issue Summary

Images are cut off on the plumber menu as if there are more options if you scroll, but you can't. Dispensers also default to pills even if you try to set it to dispense anything else, and images are missing from dispenser.

## Round ID:  
[221119](https://scrubby.melonmesa.com/round/221119)

## Testmerges:
* [#80073: 'Epic RPD Update: Multiple Pipe Layers With 1 Click' by 13spacemen at commit 9d2778ece7](https://www.github.com/tgstation/tgstation/pull/80073)
* [#80439: '[TM ONLY] Remove 'natural' beheading' by Mothblocks at commit ab7dae6065](https://www.github.com/tgstation/tgstation/pull/80439)

## Reproduction:

Get a chem plumber and view the menu and observe how it's cut off, or set up a dispenser, try to dispense something that isn't pills and watch it continue to default to pills.

**Comment by SyncIt21** [comment]
You need to be specific and say the UI is broken and not the actual reactions, edit your issue title and be more specific 

The plumbing RCD UI was fixed by #80549.

To change the plumbing pill press  to something else besides pills you have to select the tab AND click on the image(for e.g. to print bottles you have to select the bottle tab and click on the bottle image inside that tab).

Just changing tabs isn't sufficient. Did you try that?

**Comment by Lutowski** [comment]
> You need to be specific and say the UI is broken and not the actual reactions, edit your issue title and be more specific
> 
> The plumbing RCD UI was fixed by #80549. Have to wait for server's to update could take a while
> 
> To change the plumbing pill press to something else besides pills you have to select the tab AND click on the image(for e.g. to print bottles you have to select the bottle tab and click on the bottle image inside that tab).
> 
> Just changing tabs isn't sufficient. Did you try that?

I'm saying that the images are literally gone, you can't pick them. The UI in the plumbing dispensers are broken ontop of the plumber's UI. Even if you pick bottles or patches, it still defaults to pills. I tried wrenching and unwrenching and repeatedly setting it to something else, but it forces it to output to pills.

**Comment by SyncIt21** [comment]
So none of the problems you state about the plumbing dispenser exist. No images are missing and printing stuff besides pills also works. What exactly is the problem?

https://github.com/tgstation/tgstation/assets/110812394/fc1e5979-1f46-4da2-a88f-a7d24491d730

**Comment by Lutowski** [comment]
> So none of the problems you state about the plumbing dispenser exist. No images are missing and printing stuff besides pills also works. What exactly is the problem?
> 
>  bandicam.2023-12-26.17-26-34-878.mp4 
> Try clearing your Byond cache and reconnect. Missing images are caused by corrupt assets as well.

Hey, I'll go ahead and close this now since that got it fixed. I talked over this with other chemist friends playing on downstreams who had same issue occur with their dispensers. I think clearing cache worked because I didn't see any recently merged PRs mentioning this. Thanks!

**Comment by t3hSurge** [comment]
The pill press ui having no images is currently a live issue on Manuel. Clearing my cache did not fix it.

**Comment by Lutowski** [comment]
> The pill press ui having no images is currently a live issue on Manuel. Clearing my cache did not fix it.

![csacsacsa](https://github.com/tgstation/tgstation/assets/136726218/d3903de4-073b-42e6-a8a9-aee007136723)

Broke on me at Terry as well. Clearing cache didn't fix it this time around.
